### ISSUE TITLE
AngularCropperjsComponent.cropper is undefined

### ISSUE THREAD

**Issue by falconsapsan** [matheusdavidson/angular-cropperjs#10]
Why cropper is undefined ?
i'm use
```
    "angular-cropperjs": "0.1.5",
    "@angular/core": "5.0.0",

```
```
@ViewChild('angularCropper') public angularCropper: AngularCropperjsComponent;

    console.log(this.angularCropper)
    console.log(this.angularCropper.cropper)

    this.angularCropper.cropper.getCroppedCanvas().toBlob((blob) => {
           console.log(blob);
    });
```

![1515169548437](https://user-images.githubusercontent.com/11406271/34618019-79714ca8-f24e-11e7-9f90-3127c08e3233.jpg)

**Comment by prashantguleria** [comment]
@falconsapsan @matheusdavidson Hey, I'm getting the same problem. Did you find any solution for this?
Kindly let me know.

**Comment by JunichiOzawa** [comment]
@prashantguleria for my situation, following command did the work
```
npm install --save @types/cropperjs
```
