### ISSUE TITLE
dragMode not supported?

### ISSUE THREAD

**Issue by Maritims** [matheusdavidson/angular-cropperjs#12]
I am trying to use dragMode: 'move' in order to move the canvas instead of the crop box, but it doesn't seem to work. Is this option supported in your package?

Screenshot from https://github.com/fengyuanchen/cropper:
![image](https://user-images.githubusercontent.com/7148307/35386929-1891e17e-01ce-11e8-9dda-9ae38c9ba89b.png)

**Comment by melvas** [comment]
you should manually set option **movable** to **true** 'cause it is 'false' by default:

`this.cropperOptions = Object.assign({
            aspectRatio,
            movable: false,
            scalable: false,
            zoomable: false,
            viewMode: 1,
            checkCrossOrigin: true
        }, this.cropperOptions);`

**Comment by iusamaaziz** [comment]
I had to copy the component and related code from lib folder, and 
[Change this line](https://github.com/matheusdavidson/angular-cropperjs/blob/719024cddb44cd1dfc08f8382d135828f17ddbb9/projects/angular-cropperjs/src/lib/cropper/cropper.component.ts#L98) to `true` to get it to work.

**Comment by matheusdavidson** [comment]
Hey Guys, removed the default options that were blocking these features, it's in the latest version.
