### ISSUE TITLE
Can't access angularCropper anywhere as defined in tutorial

### ISSUE THREAD

**Issue by vinayistar** [matheusdavidson/angular-cropperjs#16]
I don't know why you told that we can use it anywhere this method. In tutorial also its mentioned. But when I do so its not accessible. It should be present in constructor. 
With `@ViewChild` cant accessible. Please update the document.

```
this.angularCropper.cropper.getCroppedCanvas().toBlob((blob) =>{
    // blob is your base64..
});
```

**Comment by matheusdavidson** [comment]
Hi, you can access it like in the docs, i use that way in many projects. 
The method ```getCroppedCanvas``` will only be available when you use cors option, as stated in the original cropper plugin.
