### ISSUE TITLE
Update Angular Dependencies

### ISSUE THREAD

**Issue by MichaelMalony** [matheusdavidson/angular-cropperjs#18]
Any chance we could get the Angular peer dependencies upped to build with Angular 5+ without npm warnings?

This is the warning I get when using Angular 5:

```
npm WARN angular-cropperjs@0.1.5 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

Maybe something like this is dist package.json:

```
"peerDependencies": {
    "@angular/core": ">= 4.0.0 <= 5.x.x",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  }
```

**Comment by matthewnewman43** [comment]
Any update on this?

**Comment by jagomf** [comment]
Still getting the peer dependency error. In my case with both `@angular/core` and `rxjs`:
```
Package "angular-cropperjs" has an incompatible peer dependency to "rxjs" (requires "^5.1.0", would install "6.2.0").
Package "angular-cropperjs" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.0.3").
```

**Comment by tplk** [comment]
I'm not sure why there's rxjs package in dependencies at all because there's not a single import from rxjs.
Also this version works okay with angular 6 even though there're warnings about unmet peer dependencies.

**Comment by luiscmas** [comment]
Are you going to update to remove Angular 7 warnings?

npm WARN angular-cropperjs@1.0.1 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-cropperjs@1.0.1 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by matheusdavidson** [comment]
updated to v14+
