### ISSUE TITLE
How to Setup Max Width and Max Height?

### ISSUE THREAD

**Issue by BamiGorengo** [matheusdavidson/angular-cropperjs#19]
I tryed alot but i cant find a way to setup a max-width and a max-height for the crop element. If i give the Wrapper Containers some limitation, the cropper still grow out if the box:. http://prntscr.com/kddy17

Any JavaScript setup inline heights and widths. Any Solution for this?

**Comment by DanielEberl** [comment]
I am trying to solve this aswell, not finding a solution yet. 
Have you found one already?

**Comment by DanielEberl** [comment]
import the following into the .scss / css file of your component or import it globally:

:host /deep/ angular-cropper .cropper img {
  width: auto !important;
  height: 400px !important;
  overflow: hidden !important;
}


replace height with your desired value

it is kind of buggy tho, ill post my final solution asap

**Comment by BamiGorengo** [comment]
This dont really solve my problem :( seems to be a js problem...

**Comment by DanielEberl** [comment]
Maybe your containers are the issue ? For me it’s working fine inside flexbox containers

**Comment by matheusdavidson** [comment]
Hi there, you need to set:
```css
.cropper img {
    max-height: {YOUR-HEIGHT}px !important;
}
```
