### ISSUE TITLE
Default Cropper Options differ from cropperjs defaults

### ISSUE THREAD

**Issue by DanielEberl** [matheusdavidson/angular-cropperjs#20]
angular-cropperjs/src/angular-cropperjs.component.ts

Line 121 
        this.cropperOptions = Object.assign({
            aspectRatio,
            **movable: false,
            scalable: false,
            zoomable: false,
            viewMode: 1,**
            checkCrossOrigin: true
}, this.cropperOptions);

Why do this options differ from the default config, that is described in the documentation of cropperjs?

I just spend an hour working out why the cropper.zoom() method is not working while rotate works.

Please update all configs to be the same as the original cropperjs libary.

**Comment by matheusdavidson** [comment]
Hi there, i am currently rewriting the lib with ng6, update coming soon

**Comment by DanielEberl** [comment]
And by the way, thank you for this library. Maybe my post seemed a bit harsh, sorry for that.

And thank you for your quick response!
