### ISSUE TITLE
Module '".../node_modules/angular-cropperjs/angular-cropperjs"' has no exported member 'AngularCropperjsComponent'.

### ISSUE THREAD

**Issue by mateotherock** [matheusdavidson/angular-cropperjs#25]
The error in the title is the error I get when using version 1.0.1 of this library with ionic/angular. If I downgrade to 0.1.5, this particular component of our app works just fine. This is actually the resolution I get when googling this particular issue that others have found. The problem is that I actually need to use the newest version 1.0.1 as the downgraded version was not working with the rest of our application. 
I should mention that I am using Ionic 3 here and it sounds like this was an issue many people were getting with Ionic 3 so I'm guessing that might have something to do with it. 
Any idea what might be causing this? Thank you very much for this library btw!

**Comment by matheusdavidson** [comment]
Sorry, version 1+ will work only with angular 6+, you are using ionic 3 which uses angular 5

**Comment by matheusdavidson** [comment]
It should work with ionic 4

**Comment by mateotherock** [comment]
Ah, thank you for the quick response! That is a bummer, but totally understandable.
