### ISSUE TITLE
angular-cropperjs"' has no exported member 'AngularC ropperjsComponent'

### ISSUE THREAD

**Issue by Nelife** [matheusdavidson/angular-cropperjs#26]
Hello. I have a problem.
I use @angular/core: 6.1.7
Went i add 'AngularCropperjsComponent' to component, i have a error.
![image](https://user-images.githubusercontent.com/12018657/45408101-94f0ee00-b695-11e8-98a8-63c7b97582b3.png)
Please help me. Thank you so much.

**Comment by Nelife** [comment]
I fix it.
Change AngularCropperjsComponent to CropperComponent

**Comment by matheusdavidson** [comment]
Sorry for that, i updated the component but not the doc yet.

**Comment by ElizaKsajikyan** [comment]
hello Is this module work with angular 7?
