### ISSUE TITLE
How to export the cropped image

### ISSUE THREAD

**Issue by ahsanaasim** [matheusdavidson/angular-cropperjs#3]
I can see an export eventEmitter for the cropper. But not sure how to use it. Can you post an example about how to export the cropped image as blob & base64 data?

**Comment by matheusdavidson** [comment]
Hi there, thank you for posting your question. 

You need to follow the readme.md, there is a part showing how to use cropperjs methods:

**Using CropperJS methods:**

Use @ViewChild in your component to get the element:

*In your app.component.html*
```html
<angular-cropper #angularCropper ..>
```

*And in your app.component.ts*
```js

//
// Import AngularCropperjsComponent
import { AngularCropperjsComponent } from 'angular-cropperjs';

//
// Get with @ViewChild
@ViewChild('angularCropper') public angularCropper: AngularCropperjsComponent;
```

Then just call the CropperJS method you want:

*anywhere in your app.component.ts*
```js

//
// Get base64
this.angularCropper.cropper.getCroppedCanvas().toBlob((blob) =>{
    // blob is your base64..
});
```

**Comment by ahsanaasim** [comment]
Thanks for the reply. 

I tried this code before but getting this error

Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

![screen shot 2017-09-28 at 1 57 34 pm](https://user-images.githubusercontent.com/17532073/30955486-9d30f248-a455-11e7-99cf-4078cf7c2675.png)

**Comment by matheusdavidson** [comment]
Are you using checkCrossOrigin? you need to use it otherwise toBlob won't work.

**Comment by matheusdavidson** [comment]
see this: https://github.com/fengyuanchen/cropper/issues/119

**Comment by ahsanaasim** [comment]
this is what i used for cropperOptions
`this.angularCropper.cropperOptions = {
      checkCrossOrigin: false,
    };`

**Comment by matheusdavidson** [comment]
Remove checkCrossOrigin(it default to true), leave the config empty {} for now and it will work

**Comment by ahsanaasim** [comment]
But problem is my image is coming from a separate domain that. So i needed to set checkCrossOrigin to false;

**Comment by ahsanaasim** [comment]
I solved the problem by allowing cors from server end. Thanks

**Comment by matheusdavidson** [comment]
Good to hear, unfortunately that is a security limilation of the browser, not the plugin.

**Comment by Coolhat1177** [comment]
node_modules/angular-cropperjs/angular-cropperjs"' has no exported member 'AngularCropperjsComponent'.  why this error is coming

**Comment by matheusdavidson** [comment]
@Coolhat1177, please open a new issue with this bug
