### ISSUE TITLE
Not working with angular 6

### ISSUE THREAD

**Issue by tejnarayan831** [matheusdavidson/angular-cropperjs#30]
Followed  the instruction provided to use this package,but i am getting an error in the component where i want to import "AngularCropperjsComponent" ,error mentioned below: 
**node_modules/angular-cropperjs/angular-cropperjs"' has no exported member 'AngularCropperjsComponent'.**

Component is not generated by executing the below command:
npm install angular-cropperjs --save

Help me out to solve the problem!!

**Comment by matheusdavidson** [comment]
Duplicate #26

**Comment by tejnarayan831** [comment]
> Duplicate #26

Thank you
