### ISSUE TITLE
cropperjs module is not found

### ISSUE THREAD

**Issue by tejnarayan831** [matheusdavidson/angular-cropperjs#31]
After running ,the command below:
npm run build

I am getting this issue:

 **Error in node_modules/angular-cropperjs/lib/cropper/cropper.component.d.ts: can't find module cropperjs**

Please help me out to resolve the issue,Thank you in advance.

**Comment by nkCreation** [comment]
resolved by doing npm install cropperjs from my side. but the doc is not up to date apparently... and the readme is not correct anymore

**Comment by matheusdavidson** [comment]
Hi all, i will update the docs, a warning should appear in npm install showing the problem thow

**Comment by Hakog** [comment]
Why must we manual install the cropperjs lib manually ? It is part of the dependencies of this library.

**Comment by malikadilofficial** [comment]
Resolved just run command in terminal: npm i cropperjs
