### ISSUE TITLE
Can't crop smoothy

### ISSUE THREAD

**Issue by SlimEmShady** [matheusdavidson/angular-cropperjs#34]
Hey guys, great plugin around here !

But i don't understand why, i can't crop images smoothy. It's really not ergonomic... 

I made a video to show you but I can't post it, so I'll try to explain :/

Here my problem:
When i want to zoom my image, or perform any action on it (zoom in, zoom out, move the square, resize it) it just does it but really slowly, by little movements but never in one shot. I don't know if you guys see what I mean...

Right, just made a GIF, it'll be better ^^
https://gph.is/2BzIH1M

Thanks guys !

EDIT : Just to add an information -> It's smooth and really usable on iOS but on Android it's just blocking after moving some pixels...

**Comment by doroudi** [comment]
according to [this](https://github.com/fengyuanchen/cropperjs/issues/143#issuecomment-406210438) answer, you can use (touchstart) event to fix this issue:

```
<angular-cropper (touchstart)="cropperTouchStart($event)" (ready)="readyCrop($event)" #angularCropper [cropperOptions]="cropperOptions" [imageUrl]="this.URI"></angular-cropper>

  cropperTouchStart(event){
    event.stopPropagation();
    event.preventDefault(); //Most important
  }
```

**Comment by SlimEmShady** [comment]
Best solution so far !
Thanks @doroudi !
Didn't have time to test it, but I just did and it works like a charm ! :)
