### ISSUE TITLE
Pending console.log to remove

### ISSUE THREAD

**Issue by xavimurcia** [matheusdavidson/angular-cropperjs#50]
Line 66 `angular-cropper.js`

````
//
        // Add crossOrigin?
        console.log('this.cropperOptions', this.cropperOptions);
        if (this.cropperOptions.checkCrossOrigin)
            image.crossOrigin = 'anonymous';
        //
        // Image on ready event

**Comment by MaccabeeY** [comment]
In tag "v1.0.1" within ' angular-cropperjs/projects/angular-cropperjs/src/lib/cropper/cropper.component.ts ' on line 62 there is a console.log added.

In master it has been removed.  Would you create a new tag for the current master?

Thanks for all the hard work in this repo...

--
MaccabeeY

**Comment by matheusdavidson** [comment]
removed
