### ISSUE TITLE
New tag for console.log removal in master?

### ISSUE THREAD

**Issue by MaccabeeY** [matheusdavidson/angular-cropperjs#53]
In tag "v1.0.1" within ' angular-cropperjs/projects/angular-cropperjs/src/lib/cropper/cropper.component.ts ' on line 62 there is a console.log added.

In master it has been removed.  Would you create a new tag for the current master?

Thanks for all the hard work in this repo...
--
MaccabeeY

**Comment by matheusdavidson** [comment]
removed
