### ISSUE TITLE
npm WARN angular-cropperjs@1.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed

### ISSUE THREAD

**Issue by suhailkc** [matheusdavidson/angular-cropperjs#59]
Angular version 9.1.0

Showing warning when npm install :

`npm WARN angular-cropperjs@1.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

`npm WARN angular-cropperjs@1.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

[screenshot: https://ibb.co/94ZF03N](https://ibb.co/94ZF03N)

**Comment by sprengerst** [comment]
I also have the same problem.

**Comment by rruffer** [comment]
I have the same problem. and this generates error when using ng update. It does not let you update the angle because of this. Then I have to remove the angular-cropper dependency, update the project and then add the dependency again.

**Comment by hbsfaria** [comment]
This issue is old, but if anyone encounters this error while updating Angular, you can force the update with, for example, `npx @angular/cli@13 update @angular/core@13 @angular/cli@13 --force`.

Despite the dependency warnings, I'm using this library with Angular 12, and it works.
