### ISSUE TITLE
Upgrade to latest version

### ISSUE THREAD

**Issue by mhadaily** [matheusdavidson/angular-cropperjs#6]
Hi, do you have any plan to upgrade and keep the library always up to date? and do you need probably help?

thank you

**Comment by matheusdavidson** [comment]
Hi, i will maintain this lib. I am currently rewriting to make it easier for updates, so i will update to latest version. Pull requests are welcome.

**Comment by mhadaily** [comment]
Perfect, do you have an estimation of the newer version? and what do you need that I can help probably?

**Comment by matheusdavidson** [comment]
which version are saying? angular? cropperjs? im asking because the lib is not that old, it should be near the lastest versions already.

**Comment by mhadaily** [comment]
croppsJs actually,

**Comment by matheusdavidson** [comment]
You can help by implementing any new features you would like to use that is not yet possible, then send you pr.

**Comment by mhadaily** [comment]
awesome, I'll do that then
thank you

**Comment by matheusdavidson** [comment]
i think cropperjs is already the latest version.

**Comment by mhadaily** [comment]
I think js is up to date but css within your package is not.

**Comment by matheusdavidson** [comment]
i`m using in my projects, look:
```
  "_from": "cropperjs@^1.0.0",
  "_id": "cropperjs@1.1.3"
```

1.1.3 is the latest isn't it?

**Comment by mhadaily** [comment]
yes, it's the latest version as of now.

**Comment by matheusdavidson** [comment]
its true, i`m getting css indirectly. 
This could be a good think to help. Separate the lib css from cropperjs css so we can load it directly from cropperjs lib.
