### ISSUE TITLE
When i am trying to crop image whose image size is 64MB after cropping I am getting blank white image,

### ISSUE THREAD

**Issue by Ankitkumar7** [matheusdavidson/angular-cropperjs#64]
![Capture](https://user-images.githubusercontent.com/11002067/134176998-e74a38fc-fb4c-4268-9be6-1b39464c141f.PNG)

**Comment by Ankitkumar7** [comment]
My Config:

 this.config = {
        zoomable: true,
        rotatable: true,
        zoomOnWheel: true,
        cropBoxMovable: true,
        cropBoxResizable: true,
        dragMode: 'move',
        built: function () {
          this.zoomIndex = this.zoomIndex + 0.1
        },
        ready: function (e) {
          self.cropperInstance = self.angularCropper;
          if(self.cropperPositionObj){
            self.angularCropper.cropper.setData(self.cropperPositionObj);
            // disable cropper
            self.angularCropper.cropper.disable();
          }
        }
      }

**Comment by matheusdavidson** [comment]
This is a known issue with Cropper Js itself, you need to limit the image size, have a look at this:
https://github.com/fengyuanchen/cropperjs/issues/19

**Comment by anura-apps** [comment]
test
