### ISSUE TITLE
Rotating image and cropper (64 Mb Size) toBlob getting grey blank screen

### ISSUE THREAD

**Issue by Ankitkumar7** [matheusdavidson/angular-cropperjs#65]
Describe the bug
I am using large image of size 64 MB, When i try to rotate and crop getting grey blank screen

To Reproduce

Open Image of size 64 MB
Rotate Image
Get output from toBlob
See blob data as grey blank screen
Expected behavior
Grey Blank Screen

Screenshots
![image](https://user-images.githubusercontent.com/11002067/135851507-3ebbfb12-1850-4d6b-816c-5d160ab7c38d.png)

Desktop (please complete the following information):

Browser: Chrome
Smartphone (please complete the following information):

Not tested
Additional context
None

**Comment by matheusdavidson** [comment]
This is a known issue with Cropper JS itself, you need to limit the image size, have a look at this:
fengyuanchen/cropperjs#19
