### ISSUE TITLE
how to set previous cropped data?

### ISSUE THREAD

**Issue by hdramd** [matheusdavidson/angular-cropperjs#7]
i store previous cropped data x , y and width and height. how to and where i set it to show crop box?tnx

**Comment by matheusdavidson** [comment]
You can set all original cropper js options in ```cropperOptions```, so to set cropper data you need to set: 

```
cropperOptions.data = {
    x: number,
    y: number,
    width: number,
    height: number,
    rotate: number,
    scaleX: number,
    scaleY: number
}
```
