### ISSUE TITLE
Is this package unmaintained? 

### ISSUE THREAD

**Issue by localpcguy** [matheusdavidson/angular-cropperjs#82]
Wondering about the activity status here - is this unmaintained? Are pull requests being accepted? It's got a lot of dependency updates needed, and a need to ensure it's working with the latest v1.x version of CropperJS. 

In addition, it appears the maintainer of CropperJS is working on v2 (currently in beta), and so didn't know if that was on the radar for this project or not.

Thanks, I understand if it's not something you're maintaining anymore, if that's the case, I'd either fork it or create our own implementation, but wanted to check first.

**Comment by matheusdavidson** [comment]
Hi there, I haven't been able to do much development recently here but I'm working on a new version. 
First of all I'll release an update for newest angular and cropperjs(v1) version.

After that I'll work on a new version for cropperjs 2.
