### ISSUE TITLE
Getting CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by motohead400** [matheusdavidson/angular-cropperjs#87]
It looks like this module should be importing cropperjs via

`import Cropper from 'cropperjs/dist/cropper.esm.js';`
https://github.com/fengyuanchen/cropperjs/issues/1010

**Comment by matheusdavidson** [comment]
Hi, to fix that warning you should add cropperjs to allowedCommonJsDependencies in your angular.json:

https://bobbyhadz.com/blog/angular-commonjs-or-amd-dependencies-can-cause-optimization-bailouts#adding-the-package-to-allowedcommonjsdependencies-in-angularjson

meanwhile I’ll investigate the benefits of using the esm build

**Comment by motohead400** [comment]
Hello, that just removes the warning but doesn't fix the problem.  As it states, dependencies on commonjs cause optimization bailouts, so that dependency will cause a much larger package.

**Comment by motohead400** [comment]
Hi, any word on this?
